### ISSUE TITLE
Can't use OPC Twin module as IoT Edge module with opc iot services

### ISSUE THREAD

**Issue by mma-mm** [Azure/azure-iiot-opc-twin-module#3]
Hi,

i tried using the [azure iiot services](https://github.com/Azure/azure-iiot-services) with the opc twin module as edge module.
How do i need to configure this to work?

As far as i understood this, the demo works using the cli for the iiot-opc-twin-module.
This creates an Edge device (demo) which has a module (demo) in it. Then it starts the actual iiot-opc-twin-module with the iothub connection string for the module. Correct?

If i want to deploy the iiot-opc-twin-module to an existing iot edge device with the actual iotedge runtime, then the module gets the edgehub connection string. How can the iiot-services then communicate with the module? As far as i remember, Cloud to device messages for modules connected with an edge hub don't work (yet). Do i miss anything here?

Thank you for your help.
Best regards

Matthias

**Comment by marcschier** [comment]
Hi @mma-mm, there are 2 module images.  mcr.microsoft.com/iotedge/opc-twin:2.0 is the module to deploy to edge.  mcr.microsoft.com/iotedge/opc-twin:host-latest is a standalone wrapper around the module for e.g.

- Running in simulation contexts where you need more than one module running on a VM or your development machine, e.g. using different networks and scaling using docker-compose.  
- Debugging your edge setup where you want to exclude iot edge from the equation and understand whether the opc-twin and publisher just work.

As you pointed out, the wrapper is indeed the CLI in this repo.  It is a wrapper since it needs access to the iothubowner connection string, which must not be used in production and thus in production you would not use this approach.   In production, the iot edge agent through the edgelet provide the module with its connection string (components) through environment variables and the secret through the secure edgelet.

Device method calls to edge modules works just fine - it is a sort of request/response service/RPC mechanism.   What is not supported are "cloud to device messages" or messaging, which are not used by the module.

Would be great if you could provide us feedback as to how we can improve the documentation, or even submit a PR for the docs on https://github.com/Azure/azure-iiot-components repo.

**Comment by mma-mm** [comment]
Can i call these device methods from another edge-module? And if so, can i do this also while the edge device is offline?

**Comment by marcschier** [comment]
@mma-mm , Yes, you can call the device methods from other modules.  TMK, if the IoT Edge device is offline, but edgehub/edgeagent are running you should also be able to call device methods from module to module, but I would confirm in the IoT Edge project or by trying it out as I have not tried this explicitly...
